gText_ObtainedTheItem::
        .string "{JPN}{STR_VAR_2}をてにいれた！$"

gText_TheBagIsFull::
        .string "{JPN}バッグがいっぱいだ……$"

gText_PutItemInPocket::
        .string "{JPN}{PLAYER}は{STR_VAR_2}を\n"
        .string "{STR_VAR_3}ポケットにしまった。$"

gText_PlayerFoundOneItem::
        .string "{JPN}{PLAYER}は{STR_VAR_2}をみつけた！$"

gText_TooBadBagIsFull::
        .string "{JPN}ざんねん！\n"
        .string "バッグがいっぱいだ……$"

gText_PlayerPutItemInBag::
        .string "{JPN}{PLAYER}は{STR_VAR_2}を\n"
        .string "バッグにしまった。$"

gText_ObtainedTheDecor::
        .string "{JPN}{STR_VAR_2}をてにいれた！$"

gText_NoRoomLeftForAnother::
        .string "{JPN}ざんねん！\n"
        .string "{STR_VAR_2}はこれいじょうおけない……$"

gText_TheDecorWasTransferredToThePC::
        .string "{JPN}{STR_VAR_2}を\n"
        .string "パソコンにおくった。$"

gText_ObtainedTheItems::
        .string "{JPN}{STR_VAR_2}を{STR_VAR_1}こてにいれた！$"

gText_PlayerFoundItems::
        .string "{JPN}{PLAYER}は{STR_VAR_2}を\n"
        .string "{STR_VAR_1}こみつけた！$"

gText_PutCoinsAwayInCoinCase::
        .string "{JPN}{PLAYER}はコインを\n"
        .string "コインケースにしまった。$"

gText_FoundXCoins::
        .string "{JPN}{PLAYER}はコインを\n"
        .string "{STR_VAR_1}まいみつけた！$"

gText_FoundXItems::
        .string "{JPN}{PLAYER}は{STR_VAR_2}を\n"
        .string "{STR_VAR_1}こみつけた！$"

gText_CoinCaseIsFull::
        .string "{JPN}ざんねん！\n"
        .string "コインケースがいっぱいだ……$"

gText_NothingToPutThemIn::
        .string "{JPN}ざんねん！\n"
        .string "いれるものがない……$"
