gText_PkmnTransferredSomeonesPC::
	.string "{JPN}{STR_VAR_2}は パソコンへ\n"
	.string "おくられた。\p"
	.string "ボックス {STR_VAR_1}に\n"
	.string "あずけられた。$"

gText_PkmnTransferredLanettesPC::
	.string "{JPN}{STR_VAR_2}は パソコンへ\n"
	.string "おくられた。\p"
	.string "ボックス {STR_VAR_1}に\n"
	.string "あずけられた。$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "{JPN}ボックス {STR_VAR_3}が\n"
	.string "いっぱいだった。\p"
	.string "{STR_VAR_2}は ボックス {STR_VAR_1}に\n"
	.string "おくられた。$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "{JPN}ボックス {STR_VAR_3}が\n"
	.string "いっぱいだった。\p"
	.string "{STR_VAR_2}は ボックス {STR_VAR_1}に\n"
	.string "おくられた。$"

gText_PkmnSentToPCAfterCatch::
	.string "{JPN}{STR_VAR_2}は パソコンへ\n"
	.string "おくられた。\p"
	.string "ボックス {STR_VAR_1}に\n"
	.string "あずけられた。$"

gText_PlayerObtainedTheMon::
	.string "{PLAYER} obtained\n"
	.string "the {STR_VAR_1}!$"

gText_NoMoreRoomForPokemon::
	.string "There's no more room for POKéMON!\p"
	.string "The POKéMON BOXES are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon::
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
