GoldenrodCity_RadioTower_4F_hns_MapScripts::
	.byte 0

GoldenrodCity_RadioTower_4F4_EventScript_Sign1::
	lock
	msgbox GoldenrodCity_RadioTower_4F4_Text_Studio2Sign, MSGBOX_SIGN
	closemessage
	release
	end

GoldenrodCity_RadioTower_4F4_EventScript_Sign2::
	lock
	msgbox GoldenrodCity_RadioTower_4F4_Text_ProductionSign, MSGBOX_SIGN
	closemessage
	release
	end

GoldenrodRaidoTower4_EventScript_Grunt28::
	trainerbattle_single TRAINER_GRUNT_28_HNS, GoldenrodCity_RadioTower_4F4_Text_GruntF4Seen, GoldenrodCity_RadioTower_4F4_Text_GruntF4Beaten
	msgbox GoldenrodCity_RadioTower_4F4_Text_GruntF4After, MSGBOX_AUTOCLOSE
	end

GoldenrodRaidoTower4_EventScript_Grunt9::
	trainerbattle_single TRAINER_GRUNT_9_HNS, GoldenrodCity_RadioTower_4F4_Text_GruntM10Seen, GoldenrodCity_RadioTower_4F4_Text_GruntM10Beaten
	msgbox GoldenrodCity_RadioTower_4F4_Text_GruntM10After, MSGBOX_AUTOCLOSE
	end

GoldenrodRaidoTower4_EventScript_Proton::
	trainerbattle_single TRAINER_PROTON_2_HNS, GoldenrodCity_RadioTower_4F4_Text_Proton_Seen, GoldenrodCity_RadioTower_4F4_Text_Proton_Beaten
	msgbox GoldenrodCity_RadioTower_4F4_Text_Proton_After, MSGBOX_AUTOCLOSE
	end


GoldenrodCity_RadioTower_4F4_EventScript_Fisher::
	lock
	faceplayer
	msgbox GoldenrodCity_RadioTower_4F4_Text_Fisher, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_RadioTower_4F4_EventScript_Scientist::
	trainerbattle_single TRAINER_RICH_HNS, GoldenrodCity_RadioTower_4F4_Text_ScientistRichSeen, GoldenrodCity_RadioTower_4F4_Text_ScientistRichBeaten
	msgbox GoldenrodCity_RadioTower_4F4_Text_ScientistRichAfter, MSGBOX_AUTOCLOSE
	end


GoldenrodCity_RadioTower_4F4_EventScript_Mary::
	lock
	faceplayer
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 6, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 7, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 8, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
	goto_if_eq VAR_GOLDENROD_CITY_STATE, 9, GoldenrodCity_RadioTower_4F4_EventScript_Mary2
	goto_if_unset FLAG_GOT_MARY_BRIGHT_POWDER, GoldenrodCity_RadioTower_4F4_EventScript_Mary3
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMaryAfter, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_RadioTower_4F4_EventScript_Mary2::
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMary, MSGBOX_DEFAULT
	closemessage
	release
	end

GoldenrodCity_RadioTower_4F4_EventScript_Mary3::
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMaryCleared, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_BRIGHT_POWDER
	goto_if_eq VAR_RESULT, FALSE, Common_EventScript_BagIsFull
	msgbox GoldenrodCity_RadioTower_4F4_Text_DJMaryPinkBow, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_GOT_MARY_BRIGHT_POWDER
	closemessage
	release
	end

GoldenrodCity_RadioTower_4F4_EventScript_Meowth::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MEOWTH, CRY_MODE_NORMAL
	msgbox GoldenrodCity_RadioTower_4F4_Text_Meowth, MSGBOX_DEFAULT
	waitmoncry
	release
	end


GoldenrodCity_RadioTower_4F4_Text_Proton_Seen:
	.string "{JPN}ランス:ちょっとまてよ！\p"
	.string "おまえヤドンのいどでおれたちのじゃ\n"
	.string "まをしたやつじゃないか？\p"
	.string "なるほど……おれをいからせたいから\n"
	.string "こんなことをしているんだな。きをつ\l"
	.string "けろ！\p"
	.string "だがそうのぞんでいるようだからロケ\n"
	.string "ットだんかんぶのいかりのぜんぼうを\l"
	.string "おもいしらせてやる！$"

GoldenrodCity_RadioTower_4F4_Text_Proton_Beaten:
	.string "{JPN}ふぅ……$"

GoldenrodCity_RadioTower_4F4_Text_Proton_After:
	.string "{JPN}ランス:こんかいはかったかもしれな\n"
	.string "い……だがそれによって\p"
	.string "ロケットだんのいかりをさらにつのら\n"
	.string "せてしまっただけだ。$"

GoldenrodCity_RadioTower_4F4_Text_Fisher:
	.string "I listened to the radio while I was\n"
	.string "at the RUINS.\p"
	.string "I heard a strange broadcast there.$"

GoldenrodCity_RadioTower_4F4_Text_DJMary:
	.string "MARY: Why? Why do I have to suffer\n"
	.string "through this?\p"
	.string "MEOWTH, help me!$"

GoldenrodCity_RadioTower_4F4_Text_DJMaryCleared:
	.string "MARY: Oh! You're my little savior!\p"
	.string "Will you take this as my thanks?$"

GoldenrodCity_RadioTower_4F4_Text_DJMaryPinkBow:
	.string "MARY: It's good for dodging the\n"
	.string "enemy's attacks.$"

GoldenrodCity_RadioTower_4F4_Text_DJMaryAfter:
	.string "MARY: Please tune into me on PROF.\n"
	.string "OAK'S POKéMON TALK show!$"

GoldenrodCity_RadioTower_4F4_Text_Meowth:
	.string "MEOWTH: Meowth…$"

GoldenrodCity_RadioTower_4F4_Text_GruntM10Seen:
	.string "{JPN}ディレクターをすくいだすつもりか？\p"
	.string "そんなことできるわけないだろ！おれ\n"
	.string "がおまえをぶっとばしてやるからな！$"

GoldenrodCity_RadioTower_4F4_Text_GruntM10Beaten:
	.string "{JPN}えっ！しんじられない！$"

GoldenrodCity_RadioTower_4F4_Text_GruntM10After:
	.string "{JPN}しんじられない！まけてしまった！$"

GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2Seen:
	.string "Stop! I'm known as the TEAM ROCKET\n"
	.string "fortress!\p"
	.string "You're not taking another step!$"

GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2Beaten:
	.string "The fortress came down!$"

GoldenrodCity_RadioTower_4F4_Text_ExecutiveM2After:
	.string "You've earned my respect, so here's\n"
	.string "some advice.\p"
	.string "It's not too late. You can still turn\n"
	.string "back.$"

GoldenrodCity_RadioTower_4F4_Text_GruntF4Seen:
	.string "{JPN}ポケモンってかわいいとおもわない？\p"
	.string "わたしのポケモンがかわいいとおもう\n"
	.string "よ……\p"
	.string "きみのポケモンをたおしてからね！$"

GoldenrodCity_RadioTower_4F4_Text_GruntF4Beaten:
	.string "{JPN}うわっやばい！こいつらまったくやく\n"
	.string "にたたない！$"

GoldenrodCity_RadioTower_4F4_Text_GruntF4After:
	.string "{JPN}わたしはうつくしいじぶんがだいすき\n"
	.string "！\p"
	.string "ポケモンなんてどうでもいいわ！$"

GoldenrodCity_RadioTower_4F4_Text_ScientistRichSeen:
	.string "{JPN}じつにすばらしい。\p"
	.string "このラジオタワーこそがわれわれのそ\n"
	.string "うだいなこうそうをじつげんしてくれ\l"
	.string "るだろう。$"

GoldenrodCity_RadioTower_4F4_Text_ScientistRichBeaten:
	.string "{JPN}うーん……\p"
	.string "どんなそうだいなけいかくにもつまず\n"
	.string "きはつきものだ。$"

GoldenrodCity_RadioTower_4F4_Text_ScientistRichAfter:
	.string "{JPN}ほんとうにロケットだんをやめられる\n"
	.string "とほんきでおもっているのか？$"

GoldenrodCity_RadioTower_4F4_Text_ProductionSign:
	.string "4F PRODUCTION$"

GoldenrodCity_RadioTower_4F4_Text_Studio2Sign:
	.string "4F STUDIO 2$"
